Exercice 1

In [83]:
import numpy as np

data = np.array([[[1,2,3],[4,5,6]]])
np.transpose(data, (2,0,1))



array([[[1, 4]],

       [[2, 5]],

       [[3, 6]]])

Exercice 2

In [84]:
data = np.array([[3,4,6,0,2,5,7],[13,34,42,1,13,12,48]]) 


n = np.argsort(data[0])
result = np.array([data[0, n], data[1, n]])
result

array([[ 0,  2,  3,  4,  5,  6,  7],
       [ 1, 13, 13, 34, 12, 42, 48]])

Exercice 3

In [85]:
a = np.array([ [0, 10, 200],
 [300, 400, 700],
 [800, 810, 820]])

i = np.array([ [1, 0, 2],
 [0, 2, 1],
 [2, 0, 1]])


result = np.array([a[0, i[0]], a[1, i[1]], a[2, i[2]]])
result

array([[ 10,   0, 200],
       [300, 700, 400],
       [820, 800, 810]])

Exercice 4

In [130]:
A = np.array([[301,101,201,0], [41,51,21,11]]) 
a = A[0] > A[1]
B = np.array([a, ~a])
B[:, [1,3]] = B[:, [3,1]] 
B

array([[ True, False,  True,  True],
       [False,  True, False, False]])

Exercice 5

In [87]:
A = np.array([[ 1, 2, 3, 4, 5],
[ 6, 7, 8, 9, 10],
[11, 12, 13, 14, 15],
[16, 17, 18, 19, 20]])


A[:,[0,-1]] += 2
A


array([[ 3,  2,  3,  4,  7],
       [ 8,  7,  8,  9, 12],
       [13, 12, 13, 14, 17],
       [18, 17, 18, 19, 22]])

Exercice 6

In [133]:

L = 5
H = 4

d = np.zeros((H,L))
if ( L >= 2 and H >= 1):
    d[0, [1, L - 2]] = 9.0
else :
    print("Erreur de dimmension")
d

array([[0., 9., 0., 9., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Exercice 7

In [132]:
#7

d = np.array([1,2,3,4,5,6,7,8,9,0])
m = np.array([[0,1,0,1,0,0,0,0,0,1]])

np.sort(d[np.squeeze(m) == 1])

array([0, 2, 4])