In [19]:
import numpy as np

#1

data = np.array([[[1,2,3],[4,5,6]]])
data = data.reshape(3,2)
data


array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
#2

data = np.array([[3,4,6,0,2,5,7],[13,34,42,1,13,12,48]])

n = np.argsort(data)

data[data.argsort]

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [15]:
#5 

A = np.array([[ 1, 2, 3, 4, 5],
[ 6, 7, 8, 9, 10],
[11, 12, 13, 14, 15],
[16, 17, 18, 19, 20]])


A[:,[0,-1]] += 2
A

array([[ 3,  2,  3,  4,  7],
       [ 8,  7,  8,  9, 12],
       [13, 12, 13, 14, 17],
       [18, 17, 18, 19, 22]])

In [86]:
#6

L = 5
H = 4

d = np.zeros((H,L))
if ( L >= 2 and H >= 1):
    d[0, [1, L - 2]] = 9.0
else :
    print("Erreur de dimmension")
d

array([[0., 9., 0., 9., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [69]:
#7

d = np.array([1,2,3,4,5,6,7,8,9,0])
m = np.array([[0,1,0,1,0,0,0,0,0,1]])

np.sort(d[np.squeeze(m) == 1])

array([0, 2, 4])